// Generated by IcedCoffeeScript 1.8.0-d
var Scheduler, futureCheck, i, scheduler, _i;

Scheduler = require('./index');

scheduler = new Scheduler({
  host: 'localhost',
  port: 6379,
  pass: 'hello'
});

futureCheck = function(err, key) {
  return console.log("futureCheck " + key);
};

for (i = _i = 0; _i < 10; i = ++_i) {
  scheduler.schedule({
    key: "john-" + i,
    expire: i * 1000,
    handler: futureCheck
  }, function(err) {
    return console.log('scheduled');
  });
}

setTimeout((function() {
  return scheduler.cancel({
    key: 'john-7'
  }, function(err) {
    return console.log('cancelled');
  });
}), 2500);
